"""jos

Revision ID: 4c389e791d43
Revises: 
Create Date: 2020-08-14 16:09:17.582726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c389e791d43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laGou',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_addr', sa.String(length=128), nullable=True),
    sa.Column('job_name', sa.String(length=128), nullable=True),
    sa.Column('detail_url', sa.String(length=64), nullable=True),
    sa.Column('data_from', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laGou')
    # ### end Alembic commands ###
